FROM debian:latest

ENV USER=dq
ENV UID=1000
ENV GNAME=dq
ENV GID=1000
ENV HOME=/home/dq

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

ENV PATH=${PATH}:/home/dq/sh:/home/dq/.local/bin:/vol/tools
ENV APACHE_RUN_DIR=/var/run/apache2

RUN apt update -y && apt install -y \
    apache2 \
    build-essential \
    gcc \
    curl \
    git \
    make \
    vim \
    php7.3 \
    libpq-dev \
    locales \
    net-tools \
    python3-psycopg2 \
    sudo

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen

RUN apt install -y \
    python3 \
    python3-dev \
    python3-pip

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade virtualenv
RUN pip3 install gunicorn

RUN rm -f /etc/apache2/sites-enabled/*
COPY ./rootfs /

RUN groupadd -g "${GID}" "${GNAME}" \
 && useradd -m -s /bin/bash -g "${GNAME}" -u "${UID}" "${USER}" \
 && adduser "${USER}" "sudo" \
 && chown -R "${USER}:${GID}" "${HOME}" \
 && echo "%sudo   ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/nopasswd

RUN chmod -R 777 /tmp
RUN mkdir -p "${APACHE_RUN_DIR}" \
 && chown -R ${USER} ${APACHE_RUN_DIR}

RUN useradd -m -s /bin/false apache
RUN mkdir -p /etc/httpd/vhosts.d

RUN ln -sf /usr/bin/python3 /usr/bin/python

USER ${USER}

HEALTHCHECK --timeout=5s --interval=5s --retries=3 \
   CMD curl -f http://localhost:8080 || exit 1

CMD ["/drun.sh"]
