FROM debian:latest

ENV USER=dq
ENV UID=1000
ENV GNAME=dq
ENV GID=1000
ENV HOME=/home/dq

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

ENV PATH=${PATH}:/home/dq/sh:/home/dq/.local/bin:/vol/tools
ENV WORDPRESS_PATH=/home/dq/wp/

RUN apt update -y && apt install -y \
    curl \
    git \
    php7.3 \
    php7.3-cli \
    php7.3-fpm \
    php7.3-mysql \
    php-pear \
    python3 \
    python3-dev \
    python3-pip \
    python3-psycopg2 \
    locales \
    net-tools \
    procps \
    sudo \
    vim
RUN pear install http_request2

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen

RUN pip3 install --upgrade pip && pip3 install gunicorn
RUN ln -sf /usr/bin/python3 /usr/bin/python

WORKDIR /tmp
RUN curl -O https://wordpress.org/latest.tar.gz \
 && mkdir -p "${WORDPRESS_PATH}" \
 && tar xzvf latest.tar.gz -C "${WORDPRESS_PATH}" --strip-components=1
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
 && chmod +x wp-cli.phar \
 && mv wp-cli.phar /usr/bin/wp
RUN git clone \
    https://github.com/django-daiquiri/wordpress-plugin \
    ${WORDPRESS_PATH}/wp-content/plugins/daiquiri
RUN git clone \
    https://github.com/django-daiquiri/wordpress-theme \
    ${WORDPRESS_PATH}/wp-content/themes/daiquiri

COPY ./rootfs /

RUN groupadd -g "${GID}" "${GNAME}" \
 && useradd -m -s /bin/bash -g "${GNAME}" -u "${UID}" "${USER}" \
 && adduser "${USER}" "sudo" \
 && chown -R "${USER}:${GID}" "${HOME}" \
 && echo "%sudo   ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/nopasswd \
 && chmod -R 777 /tmp

USER ${USER}

HEALTHCHECK --timeout=5s --interval=5s --retries=3 \
   CMD curl -f http://localhost:9280 || exit 1

CMD ["/drun.sh"]
