[daiquiri]
wordpress_db_user = "wordpress"
wordpress_db_password = "wordpress"

[pgapp]
postgres_user = "daiquiri_app"
postgres_password = "daiquiri_app"

[pgdata]
postgres_user = "daiquiri_data"
postgres_password = "daiquiri_data"

[wpdb]
mysql_user = "wordpress"
mysql_password = "wordpress"
mysql_root_password = "somewordpress"

[rabbitmq]
rabbitmq_user = "gaia"
rabbitmq_password = "password"
rabbitmq_default_user = "admin"
rabbitmq_default_pass = "admin"
