FROM postgres:latest

ENV PATH="${PATH}:/opt:/vol/tools/shed"

RUN apt update -y && apt install -y \
    postgresql-client

# create DB, user, permissions

# not necessary, but for sake of clarity
CMD ["postgres"]
